server:
  port: 8888
  servlet:
    context-path: /api


spring:
  application:
    name: mock-sever-api
  datasource:
    url: jdbc:mysql://localhost:3306/mock_server?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
    database-change-log-table: database_changelog
    database-change-log-lock-table: database_changelog_lock
  jpa:
    show-sql: false

---
spring:
  data:
    mongodb:
      database: mock_schema
      host: localhost
      port: 27017
      username: root
      password: 123456
      authentication-database: admin


