spring:
  application:
    name: mock-sever-api
  datasource:
    url: jdbc:mysql://localhost:3306/mock_server?useSSL=false
    username: root
    password: 123456

server:
  port: 8888
  servlet:
    context-path: /api

